version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    
    working_directory: ~/circleci-spring-jenkins-kubernetes # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      - setup_remote_docker # to run docker build commands in the remote circle ci machine

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: circleci-spring-jenkins-kubernetes-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline # gets the project dependencies
      
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-spring-jenkins-kubernetes-{{ checksum "pom.xml" }}
      
      - run: mvn package # run the actual tests
      
      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
      # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: target/surefire-reports
      
      - store_artifacts: # store the uberjar as an artifact
      # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/demo-0.0.1-SNAPSHOT.jar
      - run:
          name: Build and tag docker image
          command: |
            docker build -t springboot-jenkins:latest .
            docker tag springboot-jenkins hiteshjoshi1/springboot-jenkins:latest
  
  # new workflow step
  publish-dockerhub:
    
    docker: # executor base image
      - image: circleci/buildpack-deps:stretch 
    steps:
       - setup_remote_docker
       - run:
           name: Push docker image to Docker Hub # DOCKERHUB_PASS and DOCKERHUB_USERNAME are environment variables created in project for circleci
           command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker push hiteshjoshi1/springboot-jenkins:latest
workflows:
  version: 2
     build-push-dockerhub:
       jobs:
          - build
          - publish-dockerhub:
              requires:
                - build        

