---
- name: Create Deployment and Services on Kubernetes Master
  hosts: kubernetes
  become: true
  user: root

  tasks:
    - name: create a deployment
      command: kubectl apply -f deployment.yml

    - name: update deployment with new pods if image updated in docker hub
      command: kubectl rollout restart deployment.v1.apps/demo-deployment

    - name: create a service
      command: kubectl apply -f service.yml
